---
# not really a "horizon service" but horizon is the outlier
- name: restart horizon services
  restart_if_present: service=apache2

- name: restart apache
  restart_if_present: service=apache2

- name: compress horizon assets
  command: sudo -u www-data tools/with_venv.sh ./manage.py compress
           chdir=/opt/stack/horizon/
