---
nova:
  patches:
  compute_driver: nova.virt.libvirt.LibvirtDriver
  firewall_driver: nova.virt.firewall.NoopFirewallDriver
  scheduler_host_manager: nova.scheduler.host_manager.HostManager
  compute_manager: nova.compute.manager.ComputeManager
  api_workers: 5
  conductor_workers: 5
  metadata_api_workers: 5
  ec2_workers: 5
  cpu_allocation_ratio: 1.0
  ram_allocation_ratio: 1.0
  libvirt_cpu_model: null
  libvirt_type: kvm
  enable_ssh: False
  novnc_method: git
  novnc_repo: https://github.com/kanaka/noVNC.git
  novnc_rev: 292f6a5d
  novnc_url: https://github.com/kanaka/noVNC/archive/v0.5.1.tar.gz
  scheduler_default_filters: AvailabilityZoneFilter,RamFilter,ComputeFilter,CoreFilter
  libvirt_bin_version: 1.2.2-0ubuntu13.1.6~cloud2
  python_libvirt_version: 1.2.2-0ubuntu2~cloud0
  qemu_kvm_version: 2.0.0+dfsg-2ubuntu1.6~cloud0
  librdb1_version: 0.80.5-0ubuntu0.14.04.1~cloud0
  trusty:
    libvirt_bin_version: 1.2.2-0ubuntu13.1.7
    python_libvirt_version: 1.2.2-0ubuntu2
    qemu_kvm_version: 2.0.0+dfsg-2ubuntu1.9
  driver:
    docker:
      rev: 2f23a09ba49bfafedc712b82613417da7147c5a3
      git_mirror: https://github.com/stackforge/nova-docker.git
      dest: /opt/stack/novadocker

  source:
    rev: '8526a727dc20a96d7245ae836e81c29967166f77'
  package:
    console_scripts:
      - nova-all
      - nova-api
      - nova-api-ec2
      - nova-api-metadata
      - nova-api-os-compute
      - nova-baremetal-deploy-helper
      - nova-baremetal-manage
      - nova-cells
      - nova-cert
      - nova-compute
      - nova-conductor
      - nova-console
      - nova-consoleauth
      - nova-dhcpbridge
      - nova-idmapshift
      - nova-manage
      - nova-network
      - nova-novncproxy
      - nova-objectstore
      - nova-rootwrap
      - nova-scheduler
      - nova-serialproxy
      - nova-spicehtml5proxy
      - nova-xvpvncproxy

  logs:
    - paths:
        - /var/log/nova/nova-api.log
      fields:
        type: openstack
        tags: nova,nova-api
    - paths:
        - /var/log/nova/nova-cert.log
      fields:
        type: openstack
        tags: nova,nova-cert
    - paths:
        - /var/log/nova/nova-compute.log
      fields:
        type: openstack
        tags: nova,nova-compute
    - paths:
        - /var/log/nova/nova-conductor.log
      fields:
        type: openstack
        tags: nova,nova-conductor
    - paths:
        - /var/log/nova/nova-consoleauth.log
      fields:
        type: openstack
        tags: nova,nova-consoleauth
    - paths:
        - /var/log/nova/nova-manage.log
      fields:
        type: openstack
        tags: nova,nova-manage
    - paths:
        - /var/log/nova/nova-scheduler.log
      fields:
        type: openstack
        tags: nova,nova-scheduler
  logging:
    debug: False
    verbose: True
