---
neutron:
  api_workers: 3
  metadata_workers: 3
  agent_down_time: 20
  report_interval: 4
  dhcp_dns_servers:
    - 8.8.8.8
    - 8.8.4.4
  service_plugins:
    - neutron.services.l3_router.l3_router_plugin.L3RouterPlugin
  enable_flat_networks: False
  alembic_version: 0.7.0

  source:
    rev: 'dbeaa70172bc2f40e587c5e2f62bb28b600b7e25'
  package:
    console_scripts:
      - neutron-check-nsx-config
      - neutron-cisco-cfg-agent
      - neutron-db-manage
      - neutron-debug
      - neutron-dhcp-agent
      - neutron-hyperv-agent
      - neutron-ibm-agent
      - neutron-l3-agent
      - neutron-lbaas-agent
      - neutron-linuxbridge-agent
      - neutron-metadata-agent
      - neutron-metering-agent
      - neutron-mlnx-agent
      - neutron-nec-agent
      - neutron-netns-cleanup
      - neutron-ns-metadata-proxy
      - neutron-nsx-manage
      - neutron-nvsd-agent
      - neutron-ofagent-agent
      - neutron-openvswitch-agent
      - neutron-ovs-cleanup
      - neutron-rootwrap
      - neutron-rootwrap-xen-dom0
      - neutron-ryu-agent
      - neutron-sanity-check
      - neutron-server
      - neutron-sriov-nic-agent
      - neutron-usage-audit
      - neutron-vpn-agent

  logs:
    - paths:
        - /var/log/neutron/neutron-server.log
      fields:
        type: openstack
        tags: neutron,neutron-server
    - paths:
        - /var/log/neutron/neutron-dhcp-agent.log
      fields:
        type: openstack
        tags: neutron,neutron-dhcp-agent
    - paths:
        - /var/log/neutron/neutron-l3-agent.log
      fields:
        type: openstack
        tags: neutron,neutron-l3-agent
    - paths:
        - /var/log/neutron/neutron-metadata-agent.log
      fields:
        type: openstack
        tags: neutron,neutron-metadata-agent
  logging:
    debug: False
    verbose: True
