---
- name: install apache
  apt: pkg={{ item }}
  with_items:
    - apache2
    - libapache2-mod-wsgi

- name: lesscpy must be in apache PATH
  pip: name=lesscpy version=0.9j

- name: disable apache status
  command: a2dismod status
  notify:
    - restart apache

- name: apache ports config
  template: src=etc/apache2/ports.conf
            dest=/etc/apache2/ports.conf
  notify:
    - restart apache

- name: disable default apache site
  command: a2dissite 000-default
  notify:
    - restart apache

- name: openstack dashboard config (12.04)
  template: src=etc/apache2/sites-available/openstack_dashboard.conf
            dest=/etc/apache2/sites-available/openstack_dashboard
  when: ansible_distribution_version == "12.04"
  notify:
    - restart apache

- name: openstack dashboard config
  template: src=etc/apache2/sites-available/openstack_dashboard.conf
            dest=/etc/apache2/sites-available/openstack_dashboard.conf
  when: ansible_distribution_version != "12.04"
  notify:
    - restart apache

- name: enable horizon apache site
  command: a2ensite openstack_dashboard
  notify:
    - restart apache

- name: static asset directories
  file: dest={{ item }}
        state=directory
        owner=www-data
        group=www-data
        mode=0755
  with_items:
    - /opt/stack/horizon/static
    - /opt/stack/horizon/static/dashboard

- name: horizon local settings
  template: src=opt/stack/horizon/openstack_dashboard/local/local_settings.py
            dest=/opt/stack/horizon/openstack_dashboard/local/local_settings.py
            mode=0644
  notify:
    - restart apache

- name: custom horizon logo
  get_url: url={{ horizon.logo_url }}
           dest=/opt/stack/horizon/openstack_dashboard/static/dashboard/img/logo.png
           mode=0644 force=yes

- name: custom horizon splash logo
  get_url: url={{ horizon.logo_url }}
           dest=/opt/stack/horizon/openstack_dashboard/static/dashboard/img/logo-splash.png
           mode=0644 force=yes

- name: custom horizon favicon
  get_url: url={{ horizon.favicon_url }}
           dest=/opt/stack/horizon/openstack_dashboard/static/dashboard/img/favicon.ico
           force=yes

- name: put images and fonts where apache can find them
  file: src=/opt/stack/horizon/openstack_dashboard/static/dashboard/{{ item }}
        dest=/opt/stack/horizon/static/dashboard/{{ item }}
        state=link
        owner=www-data
        group=www-data
  with_items:
    - img
    - fonts

# flush before ensuring apache running, saves immediate restart
- meta: flush_handlers

- name: ensure apache started
  service: name=apache2 state=started

- name: Permit HTTP and HTTPS
  ufw: rule=allow to_port={{ item }} proto=tcp
  with_items:
  - 80
  - 443

- include: monitoring.yml tags=monitoring,common
